// Code generated by Kitex v0.9.1. DO NOT EDIT.

package orderservice

import (
	"context"
	ai "github.com/Blue-Berrys/Tiktok_e_commerce/rpc_gen/kitex_gen/ai"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	QueryOrder(ctx context.Context, Req *ai.OrderQueryRequest, callOptions ...callopt.Option) (r *ai.OrderQueryResponse, err error)
	AutoOrder(ctx context.Context, Req *ai.AutoOrderRequest, callOptions ...callopt.Option) (r *ai.AutoOrderResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrderServiceClient struct {
	*kClient
}

func (p *kOrderServiceClient) QueryOrder(ctx context.Context, Req *ai.OrderQueryRequest, callOptions ...callopt.Option) (r *ai.OrderQueryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryOrder(ctx, Req)
}

func (p *kOrderServiceClient) AutoOrder(ctx context.Context, Req *ai.AutoOrderRequest, callOptions ...callopt.Option) (r *ai.AutoOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AutoOrder(ctx, Req)
}
